#!/bin/bash

#counter=0
counter=1
files_produced_by_iqtree_each_run=9
# first accept a path to the json parameter files of interest
read -p 'Enter path to directory with json param files: ' param_dir
for filename in "$param_dir"/*; do

#  counter=$((counter + 1))
  echo "Now simulating with parameter file: $filename"
  Rscript sim5_code.R -P "$filename"
  
 #  num_param_files=$(ls | wc -l)
  # sleep 10s
  
  cd "./processed_fastas/"
  # now use iqtree to process the aligned fasta that was generated by this run:
  most_recent_runid=$(ls -dt */ | head -n 1)

  echo "most recent run id: $most_recent_runid"
  
  cd "$most_recent_runid" || { echo "Failed to enter $most_recent_runid"; exit 1; }

  # sleep until the fasta files have been generated and written out 
  # for now, will wait until two files are written -- the aligned and unaligned
  # will eventually have to modify this according to whether the user is writing otu both of these files
  expected_num_files=$((2 * counter + files_produced_by_iqtree_each_run * (counter - 1)))

  echo "expected number of files = $expected_num_files"
  while [[ $(find . -maxdepth 1 -type f | wc -l) -lt $expected_num_files ]]; do
    echo "waiting ..."
    sleep 10 
  done

  echo "number of files in this dir == $num_files"
  
  # get name of full fasta (full meaning has entire bc seq, not just varpos)  
  full_fasta=$(ls *_FULL.fasta)

  # muscle msa the sequences in the full fasta
  msa_fasta_name="${full_fasta%.fasta}_msa.fasta"
  muscle -align "$full_fasta" -output "$msa_fasta_name"
  
  # use this new msa fasta as input to iqtree ...

 # iqtree -s "$aligned_fasta" -m MFP -bb 1000 -alrt 1000 -bcor 0.9 -nstep 80
#  iqtree -s "$full_fasta" -m MFP -bb 1000 -alrt 1000 -bcor 0.9 -nstep 80
#  iqtree -s "$full_fasta" -m HKY -bb 1000 -alrt 1000 -nstep 80 -ntmax 20
  iqtree -s "$msa_fasta_name" -m HKY -bb 1000 -alrt 1000 -nstep 80 -ntmax 20

  echo "iqtree generated tree for file: $msa_fasta_name"
  # now we don't subtract 1 from counter when finding expected num files
  echo "finding number of files ..."
  post_iqtree_expected_num_files=$((2 * counter + files_produced_by_iqtree_each_run * counter))
  echo "post iqtree expcted num files == $post_iqtree_expected_num_files"
  
  treefile_name="${msa_fasta_name}.treefile"

  echo "searching for $treefile_name"
  if [ ! -f "$treefile_name" ]; then
    echo "$treefile_name not found  yet. waiting, then will search again"
    sleep 10
  else
    echo "found $treefile_name"
  fi
  
  this_ground_truth_tree_path="../../processed_newicks/${most_recent_runid}ground_truth_tree.newick"

  # trim off the .json part
  this_savename="${filename::-5}_FULL__${counter}"

  Rscript ../../compare_trees_call_from_bash.r -R "$treefile_name" -G "$this_ground_truth_tree_path" -I "$most_recent_runid" -S "$this_savename" -F "$filename"

  echo "finished comparing recon tree to ground truth"

  cd ../../

done
