#!/bin/bash
 
base_path=$(pwd)

# initialize param_dir that will be filled
param_dir=""

# if the user provides a path to the param directory with the d flag:
if [[ "$1" == "-d" ]]; then
  param_dir="${2:-}"
fi

# if param_dir string is still empty (ie user did not provide param dir at execution)
if [[ -z "$param_dir" ]]; then
  read -p 'Enter path to directory with json param files: ' param_dir
fi


for filename in "$param_dir"/*; do
  SECONDS=0

#  counter=$((counter + 1))
  echo "Now simulating with parameter file: $filename"
  Rscript sim5_code.R -P "$filename"

  echo "Simulation alone took $SECONDS seconds"
  
 #  num_param_files=$(ls | wc -l)
  # sleep 10s
   
  # extract the most recent run id. this works because even in score-only approach,
  # reference sequences will be generated in processed_fastas 
  cd "${base_path}/output/processed_fastas/"
  # now use iqtree to process the aligned fasta that was generated by this run:
  most_recent_runid=$(ls -dt */ | head -n 1)

  # trim off trailing slash
  most_recent_runid="${most_recent_runid%/}"

  echo "most recent run id: $most_recent_runid"

  # make a new directory specific to this runid that will house the trees generated
  mkdir -p "${base_path}/output/recon_trees/${most_recent_runid}"
  
  cd "$most_recent_runid" || { echo "Failed to enter $most_recent_runid"; exit 1; }
  
  # check if any fastas are present; if not, check for 10 more seconds
  fastas_present=false
  num_times_searched=0
  max_searches=3
  
  # if there's no fasta present after three searches, check to see if score mats exist
  while [[ $fastas_present = false ]] && [[ $num_times_searched -lt $max_searches ]]; do
    ((num_times_searched++))
    if [[ $(find . -maxdepth 1 -name "*.fasta" | wc -l) -gt 0 ]]; then
      fastas_present=true
    else
      echo "waiting for the first fasta file to appear ... (Search ${num_times_searched}/${max_searches})"
      sleep 3
    fi
  done

  if $fastas_present = true; then
    
  
    # get all fasta sequences ending in TERM (including varpos, if applicable)
    # exclude any _msa.fasta files
    terminal_fastas=$(ls *_TERM.fasta | grep -v "_msa.fasta$")

    for terminal_fasta in $terminal_fastas; do
      echo "Processing $terminal_fasta"
	

      # muscle msa the sequences in the full fasta
      msa_fasta_name="${terminal_fasta%.fasta}_msa.fasta"
      muscle -align "$terminal_fasta" -output "$msa_fasta_name"

      treedir="${base_path}/output/recon_trees/${most_recent_runid}/fasta_${msa_fasta_name%.fasta}/"
      mkdir -p $treedir

      treefile_name="${treedir}fasta_${msa_fasta_name%.fasta}"
      echo "fasta treefile_name = ${treefile_name}"
  
      # use this new msa fasta as input to iqtree ...

      #  iqtree -s "$aligned_fasta" -m MFP -bb 1000 -alrt 1000 -bcor 0.9 -nstep 80
      #  iqtree -s "$full_fasta" -m MFP -bb 1000 -alrt 1000 -bcor 0.9 -nstep 80
      #  iqtree -s "$full_fasta" -m HKY -bb 1000 -alrt 1000 -nstep 80 -ntmax 20
      iqtree -s "$msa_fasta_name" -m HKY -bb 1000 -alrt 1000 -nstep 80 -nt 40 -pre $treefile_name


  
    done

  fi
  

  # unlike the processed_fasta dir, which will always exist because of reference being written to it,
  # there is no guarantee that the score mats subdirs exist
  # if it does exist, cd into it; if it doesn't, it means phylips will not be present
  
  phylip_dir="${base_path}/output/score_mats/${most_recent_runid}/phylips/"
  if [ -d "$phylip_dir" ]; then
    echo "phylip dir exists"
    cd $phylip_dir

    # check if any phylips are present; if not, check for 10 more seconds
    phylips_present=false
    num_times_searched=0
    max_searches=3
  
    # if there's no fasta present after three searches, check to see if score mats exist
    while [[ $phylips_present = false ]] && [[ $num_times_searched -lt $max_searches ]]; do
      ((num_times_searched++))
      # if [[ $(find . -maxdepth 1 -name "*.phy" | wc -l) -gt 0 ]]; then
      if [[ $(find . -maxdepth 1 -name "*.fasta" | wc -l) -gt 0 ]]; then # temporary solution of saving fastas to phylip dir
        phylips_present=true
      else
        echo "waiting for the first phylip file to appear ... (Search ${num_times_searched}/${max_searches})"
        sleep 3
      fi
    done
  else # if the phylip dir does not exist, phylips_present can be set to false
    phylips_present=false
    echo "phylip dir does not exist"
  fi
    

  if $phylips_present = true; then

    echo "pwd here == $(pwd)"

    # all_phylips=$(ls *.phy)
    # temporary solution of saving fastas to phylip dir
    all_phylips=$(ls *.fasta)

    for phy_path in $all_phylips; do
      echo "phy_path = ${phy_path}"
      # treedir="${base_path}/output/recon_trees/${most_recent_runid}/score_${phy_path%.phy}/"
      treedir="${base_path}/output/recon_trees/${most_recent_runid}/score_${phy_path%.fasta}/"
      mkdir -p $treedir

      treefile_name="${treedir}score_${phy_path%.phy}"
      
      # # don't need this conversion anymore since score mats are saved to fastas and not phylips
      # # testing conversion from .phy to .fasta:
      # fasta_path="${base_path}/output/processed_fastas/${most_recent_runid}/${phy_path%.phy}.fasta"

      # python "${base_path}/phy_to_fasta.py" --phylip_path "$phy_path" --fasta_path "$fasta_path"
      # # don't need this conversion anymore since score mats are saved to fastas and not phylips

      
      # msa_fasta_path="${fasta_path%.fasta}_msa.fasta" # REMOVING THIS FOR NOW AS I AM ONLY WORKING WITH SCORE MATS
      # REINTRODUCE IF USING NUCLEOTIDE SEQUENCES
      # muscle -align "$fasta_path" -output "$msa_fasta_path"
      # iqtree -s ${msa_fasta_path} -bb 1000 -alrt 1000 -nstep 80 -nt 40 -pre $treefile_name
      iqtree -s ${phy_path} -st BIN -m MF -pre $treefile_name

    done

  fi
  
  # now look at all those reconstructed trees from both fasta and score methods
  cd "${base_path}/output/recon_trees/${most_recent_runid}/"  
  echo "pwd here below == $(pwd)"

  # now iterate through each directory in the urid subdir of recon_trees, read in the treefile in each subdir, and compare to ground truth
  # skip the
  all_recon_dirs=$(ls -d */ 2>/dev/null || true)
  # all_recon_dirs=$(ls -d */)

  # if no recon dirs were found, can continue to processing for next param file
  if [[ -z $all_recon_dirs ]]; then
    echo "No tree reconstruction directories found. Param processing complete."
    echo "Total sim param file took $SECONDS seconds"
  fi
  for recon_tree_dir in $all_recon_dirs; do
    # it's possible that iqtree makes a results dir but not a treefile due to an error (e.g. too few sequences)
    # only try to copmare a treefile if it exists
    if ls "$recon_tree_dir"/*.treefile &> /dev/null; then
      echo "recon_tree_dir = ${recon_tree_dir}"
      cd $recon_tree_dir
      treefile_name=$(ls *.treefile)
      echo "treefile_name = ${treefile_name}"
      this_savename="${treefile_name%.treefile}"
      global_path=$(pwd)
      Rscript "${base_path}/compare_trees_call_from_bash.r" -R "$treefile_name" -I "$most_recent_runid" -S "$this_savename" -P "$filename" -T "$global_path"
      cd .. 
    fi
  done



  cd $base_path

  Rscript process_results_from_bash.r -I "$most_recent_runid" 

  Rscript convert_scoremats_to_csvs.r --urid "$most_recent_runid" --score_mat_path "${base_path}/output/score_mats/${most_recent_runid}/matrices/"

  echo "Total sim param file took $SECONDS seconds"

done
