#!/bin/bash

#counter=0
counter=1
files_produced_by_iqtree_each_run=9
# first accept a path to the json parameter files of interest
read -p 'Enter path to directory with json param files: ' param_dir
for filename in "$param_dir"/*; do

#  counter=$((counter + 1))
  echo "Now simulating with parameter file: $filename"
  Rscript sim5_code.R -P "$filename"
  
 #  num_param_files=$(ls | wc -l)
  # sleep 10s
  
  cd "./processed_fastas/"
  # now use iqtree to process the aligned fasta that was generated by this run:
  most_recent_runid=$(ls -dt */ | head -n 1)

  echo "most recent run id: $most_recent_runid"
  
  cd "$most_recent_runid" || { echo "Failed to enter $most_recent_runid"; exit 1; }

  # sleep until the fasta files have been generated and written out 
  # for now, will wait until two files are written -- the aligned and unaligned
  # will eventually have to modify this according to whether the user is writing otu both of these files
  expected_num_files=$((2 * counter + files_produced_by_iqtree_each_run * (counter - 1)))

  echo "expected number of files = $expected_num_files"
  while [[ $(find . -maxdepth 1 -type f | wc -l) -lt $expected_num_files ]]; do
    echo "waiting ..."
    sleep 10 
  done
  # echo "current diretory == $(pwd)"
  # echo "$(ls)"
  # num_files=$(ls | wc -l)

  echo "number of files in this dir == $num_files"

  aligned_fasta=$(ls *_ALIGNED.fasta)

  echo "aligned fasta name: $aligned_fasta"

  iqtree -s "$aligned_fasta" -m MFP -bb 1000 -alrt 1000 -bcor 0.9 -nstep 80

  echo "iqtree generated tree for file: $aligned_fasta"

  # now we don't subtract 1 from counter when finding expected num files
  echo "finding number of files ..."
  post_iqtree_expected_num_files=$((2 * counter + files_produced_by_iqtree_each_run * counter))
  echo "post iqtree expcted num files == $post_iqtree_expected_num_files"
  while [[ $(find . -maxdepth 1 -type f | wc -l) -lt $post_iqtree_expected_num_files ]]; do
    echo "waiting in the post iqtree expected num files while loop"
    sleep 10 
  done
  
  echo "searchng for most recent treefile"
  # define bash variable most_recent_ml_tree_path by ls -lt'ing the most recent .treefile
  most_recent_treefile=$(find "./" -type f -name "*.fasta.treefile" -printf "%T@ %p\n" | sort -n | tail -1 | cut -d' ' -f2-)

  echo "most recent tree file found: $most_recent_treefile"
  this_recon_tree_path="./${most_recent_treefile}"

  echo "pwd = $(pwd)"

  this_ground_truth_tree_path="../../processed_newicks/${most_recent_runid}ground_truth_tree.newick"

  # trim off the .json part
  this_savename="${filename::-5}_${counter}"

  Rscript ../../compare_trees_call_from_bash.r -R "$this_recon_tree_path" -G "$this_ground_truth_tree_path" -I "$most_recent_runid" -S "$this_savename" -F "$filename"

  echo "finished comparing recon tree to ground truth"

  cd ../../

done
