#!/bin/bash

# first accept a path to the json parameter files of interest
read -p 'Enter path to directory with json param files: ' param_dir
for filename in "$param_dir"/*; do

#  counter=$((counter + 1))
  echo "Now simulating with parameter file: $filename"
  Rscript sim5_code.R -P "$filename"
  
 #  num_param_files=$(ls | wc -l)
  # sleep 10s
  
  cd "./output/processed_fastas/"
  # now use iqtree to process the aligned fasta that was generated by this run:
  most_recent_runid=$(ls -dt */ | head -n 1)

  echo "most recent run id: $most_recent_runid"
  
  cd "$most_recent_runid" || { echo "Failed to enter $most_recent_runid"; exit 1; }

  # sleep until the first fasta file has been written out ...
  while [[ $(find . -maxdepth 1 -name "*.fasta" | wc -l) -lt 1 ]]; do
    echo "waiting for the first fasta file to appear ... "
    sleep 10
  done  
  
  # get all fasta sequences ending in TERMINAL (including varpos, if applicable)
  # exclude any _msa.fasta files
  terminal_fastas=$(ls *_TERMINAL.fasta | grep -v "_msa.fasta$")

  for terminal_fasta in $terminal_fastas; do
    echo "Processing $terminal_fasta"
	

    # muscle msa the sequences in the full fasta
    msa_fasta_name="${terminal_fasta%.fasta}_msa.fasta"
    muscle -align "$terminal_fasta" -output "$msa_fasta_name"
  
    # use this new msa fasta as input to iqtree ...

 #  iqtree -s "$aligned_fasta" -m MFP -bb 1000 -alrt 1000 -bcor 0.9 -nstep 80
 #  iqtree -s "$full_fasta" -m MFP -bb 1000 -alrt 1000 -bcor 0.9 -nstep 80
 #  iqtree -s "$full_fasta" -m HKY -bb 1000 -alrt 1000 -nstep 80 -ntmax 20
    iqtree -s "$msa_fasta_name" -m HKY -bb 1000 -alrt 1000 -nstep 80 -ntmax 20

    echo "iqtree generated tree for file: $msa_fasta_name"
  
    treefile_name="${msa_fasta_name}.treefile"

    echo "searching for $treefile_name"
    
    max_retries=3
    retry_count=0
    #if [ ! -f "$treefile_name" ]; then
    while [ ! -f "$treefile_name" ] && [ "$retry_count" -lt "$max_retries" ]; do
      echo "$treefile_name not found yet. waiting, then will search again"
      sleep 10
      ((retry_count++))
    done
    #else
    if [ -f "$treefile_name" ]; then
      echo "found $treefile_name"
    else
      echo "max tries reached; did not find $treefile_name"
      continue
    fi
    #fi
  
    this_ground_truth_tree_path="../../processed_newicks/${most_recent_runid}ground_truth_tree.newick"

    # trim off the .fasta
    this_savename="${terminal_fasta%.fasta}"

    Rscript ../../../compare_trees_call_from_bash.r -R "$treefile_name" -F "$terminal_fasta" -I "$most_recent_runid" -S "$this_savename" -P "$filename"

    echo "finished comparing the recon tree of ${terminal_fasta} to ground truth"
  
  done

  cd ../../../

done
